# Generated by Django 5.2.4 on 2025-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_address_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
