# Generated by Django 5.2.4 on 2025-10-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_medicine_dosage_alter_medicine_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.medicine'),
        ),
    ]
