# Generated by Django 5.2.4 on 2025-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_bed_status_bedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
