# Generated by Django 5.2.4 on 2025-10-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_bedrequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedassignment',
            name='requested_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='hospital.bedrequest'),
        ),
    ]
