# Generated by Django 5.2.4 on 2025-10-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_medicine_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
