# Generated by Django 5.2.4 on 2025-10-09 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_labrequest_result_labrequest_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='lab_results/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hospital.labrequest')),
            ],
        ),
    ]
