# Generated by Django 5.2.4 on 2025-10-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_labresultimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='age',
        ),
    ]
