# Generated by Django 5.2.4 on 2025-10-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_rename_dob_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
